### ISSUE TITLE
while import nets.googlenet, it has an import error. should add __init__.py in each folder

### ISSUE THREAD

**Issue by gyubeomim** [conan7882/GoogLeNet-Inception-tensorflow#1]
Thanks for sharing such a nice code :-) 

but when I tried to run demo you described, It occurs an importing error.

so it needs to be added that \_\_init__.py in each nets, model, utils, dataflows
after I added it as a null file, It runs well :-)

**Comment by VisintZJ** [comment]
I added __init__.py to each directory( nets, model, utils, dataflows), but it still tells me that 'No module named preprocess'. Do you know why?

**Comment by gyubeomim** [comment]
@VisintZJ 

did you exactly add **\_\_init__.py** file in your each directory??

It should be **\_\_init__.py** not **init.py**

sorry, markdown language hid my 2 underbars :-/

**Comment by conan7882** [comment]
@tigerk0430 
Sorry. I just noticed your comments and I have added __init__.py in all the folders.

Thanks for point out!
