### ISSUE TITLE
No googlenet.py in the repository

### ISSUE THREAD

**Issue by Pfaeff** [conan7882/GoogLeNet-Inception-tensorflow#2]
Hi there,

I wanted to try out the googlenet pretrained model, but it seems there is no googlenet.py in the lib/models directory. Also the googlenet.py from deeplearningmodel.net seems to be different.

Greetings

**Comment by conan7882** [comment]
It is in lib/nets/. Sorry for the confusion.

**Comment by Pfaeff** [comment]
Thank you very much!
