### ISSUE TITLE
testing use different kind image, but results are the same 'cat'

### ISSUE THREAD

**Issue by duyueshengmx** [conan7882/GoogLeNet-Inception-tensorflow#5]
Hello, Thanks for your job very much.
I have download the code and datafile 'cifar-10', After training, I predicted the file of ‘inception-cifar-epoch-99.meta’ with some different kind images, But the predicted results are the same 'cat'.
So, could you please give me some ideas?

And another question is the connect to download the pretrained GoogleNet.npy file still can not open.

**Comment by duyueshengmx** [comment]
Additional infos: I have recoveried the test photos according to you dataset of 'cifar-10-python.tar.gz', and I found the test photos are too smaller, it's hard to Identified by my eyes, So maybe this is the reason of all my predict results are 'cat'. So I want to know, how about your predict results when use your pre-trained model?
Could you please give some help? Thank you very much!

**Comment by conan7882** [comment]
You may  use the model trained on ImageNet, which can be found here:https://github.com/conan7882/GoogLeNet-Inception#imagenet-classification
