### ISSUE TITLE
LRN Layer

### ISSUE THREAD

**Issue by swghosh** [conan7882/GoogLeNet-Inception-tensorflow#8]
LRN ([Local Response Normalization](https://www.tensorflow.org/api_docs/python/tf/nn/local_response_normalization)) layers are used in the original GoogLeNet a.k.a. original Inception architecture.
```
Going deeper with convolutions.
Szegedy, Christian, et al. 
Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2015.
```
Not sure where these layers have been implemented in the source code.

Thanks in advance. Any help would be appreciated!

**Comment by conan7882** [comment]
LRN for convolutional layers are implemented here:
https://github.com/conan7882/GoogLeNet-Inception/blob/master/src/models/inception_module.py#L89
https://github.com/conan7882/GoogLeNet-Inception/blob/master/src/models/inception_module.py#L100

**Comment by swghosh** [comment]
Thanks! ✨
